name: Sync Fork

on:
  schedule:
    - cron: '39 17 * * *' # every 30 minutes
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.6.3
        with:
          owner: parkr
          repo: dotfiles
          base: main
          head: main
